// examples/solid/src/components/tailwindui/Card.tsx
import type { Component, JSX } from 'solid-js';

const Card: Component<JSX.HTMLAttributes<HTMLDivElement>> = ({
  class: classProp,
  ...props
}) => (
  <div
    class={`p-3 border border-gray-300 dark:border-gray-700 bg-gray-100 dark:bg-gray-800 rounded-xl ${classProp} flex items-start`}
    {...props}
  />
);

export default Card;

// examples/gnt/app/components/Card.tsx
import { type FunctionComponent, type HTMLAttributes } from 'react';

const Card: FunctionComponent<HTMLAttributes<HTMLDivElement>> = ({
  className,
  ...props
}) => (
  <div
    className={`p-3 my-3 border border-gray-300 dark:border-gray-700 bg-gray-100 dark:bg-gray-800 rounded-xl ${className} flex items-start`}
    {...props}
  />
);

export default Card;
