// examples/solid/src/components/Characters.tsx
import { For, createSignal, type Component } from 'solid-js';
import Avatar from '~/components/tailwindui/Avatar';
import Button from '~/components/tailwindui/Button';
import Card from '~/components/tailwindui/Card';
import SmallText from '~/components/tailwindui/SmallText';
import Text from '~/components/tailwindui/Text';
import { createQuery } from '~/gqty';

const CharacterSearch: Component = () => {
  const [searchValue, setSearchValue] = createSignal<string>();

  const { schema } = createQuery({
    // cachePolicy: 'no-cache',
  });

  return (
    <>
      <SearchBox
        onChange={(v) => {
          setSearchValue(v);
        }}
      />

      <For
        each={
          schema().query.characters(
            searchValue() ? { filter: { name: searchValue() } } : undefined
          )?.results
        }
      >
        {(item) => (
          <Card class="mb-3">
            <Avatar character={item} />

            <div class="flex-1 dark:text-white">
              <Text>
                {item?.id ?? 0}. {item?.name}
              </Text>
              <SmallText>{item?.species}</SmallText>
              <SmallText>{item?.origin?.name}</SmallText>
            </div>
          </Card>
        )}
      </For>
    </>
  );
};

const SearchBox: Component<{
  onChange?: (value: string) => void;
}> = ({ onChange }) => {
  const [inputName, setInputName] = createSignal('');

  return (
    <div class="flex gap-3 items-center mb-3">
      <input
        type="text"
        value={inputName()}
        onChange={(e) => setInputName(e.target.value)}
        class="border border-gray-300 rounded-md px-3 py-2 w-full text-black"
      />
      <Button size="lg" onClick={() => onChange?.(inputName())}>
        Search
      </Button>
    </div>
  );
};

export default CharacterSearch;

// examples/vite-react/src/App/Characters.tsx
import { type FunctionComponent } from 'react';
import { useQuery } from '../gqty';
import Avatar from './Avatar';
import Card from './Card';
import SmallText from './SmallText';
import Text from './Text';

const Characters: FunctionComponent<{
  className?: string;
  name?: string;
}> = ({ className, name }) => {
  const { characters } = useQuery({ suspense: true });

  return (
    <div className={className}>
      {characters({ filter: { name } })?.results?.map((character) => (
        <Card key={character?.id ?? '0'}>
          <Avatar character={character} />

          <div className="flex-1 text-black">
            <Text>{character?.name}</Text>
            <SmallText>{character?.species}</SmallText>
            <SmallText>{character?.origin?.name}</SmallText>
          </div>
        </Card>
      ))}
    </div>
  );
};

export default Characters;
